name: Playwright Tests

on:
  schedule:
    - cron: '0 17 * * *'
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      target_env:
        description: "Target environment"
        required: true
        default: "SIT"
        type: choice
        options:
          - SIT
          - UAT

jobs:
  tests-api:
    name: API Tests
    uses: ./.github/workflows/run-tests.yml
    with:
      workspace_type: api
      test_environment: ${{ github.event_name == 'workflow_dispatch' && inputs.target_env || vars.ENV || 'SIT' }}
      keyword: ''
      workers: '4'
    secrets: inherit

  report-api:
    name: API Report
    if: ${{ !cancelled() }}
    needs: [tests-api]
    uses: ./.github/workflows/report.yml
    with:
      workspace_type: api
      test_environment: ${{ github.event_name == 'workflow_dispatch' && inputs.target_env || vars.ENV || 'SIT' }}
      keyword: ''
      scheduler: ${{ github.event_name == 'schedule' }}
    secrets: inherit

  tests-web:
    name: Web Tests
    if: ${{ !cancelled() }}
    needs: [tests-api]
    uses: ./.github/workflows/run-tests.yml
    with:
      workspace_type: web
      test_environment: ${{ github.event_name == 'workflow_dispatch' && inputs.target_env || vars.ENV || 'SIT' }}
      keyword: ''
      workers: '4'
    secrets: inherit

  report-web:
    name: Web Report
    if: ${{ !cancelled() }}
    needs: [tests-web]
    uses: ./.github/workflows/report.yml
    with:
      workspace_type: web
      test_environment: ${{ github.event_name == 'workflow_dispatch' && inputs.target_env || vars.ENV || 'SIT' }}
      keyword: ''
      scheduler: ${{ github.event_name == 'schedule' }}
    secrets: inherit
